from build.building import *


group = SConscript(['config/SConscript',
                    'main/SConscript',
                    'linker_script/SConscript',
                    'example/SConscript'])

Return('group')
