from build.building import *

# device
DEV_INCS = ['include']
group = DefineGroup(name='device', srcs=None, incs=DEV_INCS)

# startup
DEV_SRCS = ['system_cm4f.c']
if GetDepend('CONFIG_TOOL_CHAIN_GCC') or GetDepend('CONFIG_TOOL_CHAIN_ARMCLANG'):
    DEV_SRCS += ['GCC/startup_cm4f.S']
elif GetDepend('CONFIG_TOOL_CHAIN_ICCARM'):
    DEV_SRCS += ['IAR/startup_cm4f.S']
else:
    raise Exception('Toolchain is not configured or SDK donot support the compiler')

group += DefineGroup(name='startup', srcs=DEV_SRCS, incs=None)

Return('group')
